config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  resources :users, only: [] do
    member do
      get 'api_token'
    end
  end

  # API routes
  namespace :api do
    namespace :v1 do
      resources :users do 
        resources :posts do 
          resources :comments
          resources :likes
        end
      end
    end
  end
    
  # Defines the root path route ("/")
  # root "users#index"
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :author, class_name: 'User'
  after_save :posts_number_update
  after_destroy :update_posts_counter

  # Validations
  validates :title, presence: true, length: { minimum: 1, maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # Update by use author associated with post
  def posts_number_update
    author.update(posts_counter: author.posts.all.length)
  end

  def recent_five_comments
    comments.limit(5).order(created_at: :desc)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
    render json: @posts, status: :ok
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = @post.comments.includes([:author])
    render json: @post, status: :ok
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = @post.comments.includes([:author])
  end

  def new
    @post_new = Post.new
  end

  def create
    post = Post.new(author: current_user, **post_params)
    if post.save
      redirect_to user_posts_url notice: 'Post saved'
    else
      render :new
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      'Post deleted'
    else
      'Could not delete post'
    end
    redirect_to user_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<section>
  <ul>
    <%= render @user %>
  </ul>
</section>
<section class="">
  <ul class="posts_list">
    <% @user.posts.each_with_index do |post, i| %>
      <li class="single_post">
        <div class="post-header">
          <h3>Post #<span><%= i + 1 %> </span>
            <%= link_to "/users/#{@user.id}/posts/#{post.id}" do %>
              <%= post.title %>
            <% end %> 
          </h3>
          <p><%= post.text %>...</p>
          <div>
            <span><small>Comments: <%= post.comments_counter %></small></span>
            <span><small>Likes: <%= post.likes_counter %></small> 
              <%= form_with model: @like, url: user_post_likes_path(@user.id, post.id) do |form| %>
                <div>
                  <%= form.submit 'Like' %>
                </div>
              <% end %>
            </span>
          </div>
        </div>
        <ul class="comments-container">
          <% post.recent_five_comments.each do |comment| %>
            <li>
              <p><%= comment.author.name %>:
                <span>
                  <%= comment.text %>
                </span>
              </p>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
</section>
<section>
  <p>
    <span>1</span>
    <span>Next</span>
  </p>
  <%= link_to "/users/#{@user.id}/posts/new" do %>
    <button>Add new post</button>
  <% end %> 
</section>

app/views/posts/new.html.erb
<section>
  <h1>Add new post</h1>
  <%= form_with model: @post_new, url: user_posts_path do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>
  <div>
    <%= form.submit "Add post" %>
  </div>
  <% end %>
</section>

app/views/posts/show.html.erb
<section class="posts-show">
  <div class="post-header">
    <h2><span><%= @post.title %></span> by <span><%= @user.name %></span></h2>
    <div>
      <span>Comments: <%= @post.comments_counter %></span>
      <span>Likes: <%= @post.likes_counter %></span>
    </div>
    <p><%= @post.text %></p>
  </div>
  <div>
    <% if can? :destroy, @post %>
      <%= button_to "Delete post", user_post_path, method: :delete %>
    <% end %>
  </div>
  <%= render "likes/like" %>
  <ul class="comments-container">
    <% @post.recent_five_comments.each do |comment| %>
      <li>
        <div>
          <span><%= comment.author.name %>:  </span><%= comment.text %>
        </div>
        <div>
          <% if can? :destroy, comment %>
            <%= button_to "Delete comment", user_post_comment_path(@user, @post, comment), method: :delete %>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
  <%= button_tag do %>
    <%= link_to 'Comment', new_user_post_comment_path(@user, @post) %>
  <% end %>
</section>