config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  resources :users, only: [] do
    member do
      get 'api_token'
    end
  end

  # API routes
  namespace :api do
    namespace :v1 do
      resources :users do 
        resources :posts do 
          resources :comments
          resources :likes
        end
      end
    end
  end
    
  # Defines the root path route ("/")
  # root "users#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eliteblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "users_index", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "devise_sign_in", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "posts_show", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
    <% if user_signed_in? %>
      <%= link_to 'GET YOUR API TOKEN HERE', api_token_user_path(current_user) %>
      <p><b>Welcome, </b><span><%= current_user.name %></span></p>
      <%= button_to "logout", destroy_user_session_path, method: :delete  %>
    <% end %>
    </header>
    <main class="main-container">
      <%= yield %>
    </main>
  </body>
</html>